version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-pwa"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: vue-swatches
    versions:
    - 2.1.0
